redirect:
    "/home":
        permanent: true
        url: "/"
    "/foo":
        permanent: true
        url: "/bar"
    "/abc":
        permanent: false
        url: "/def"
global:
    title: JIFLabs
